# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AmeDigital-challenge-ios' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'FSPagerView'
  pod 'Alamofire'
  pod 'AlamofireImage'

  # Pods for AmeDigital-challenge-ios

  target 'AmeDigital-challenge-iosTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AmeDigital-challenge-iosUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
